name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation SVG
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: resccrew
          outputs: |
            dist/github-contribution-grid-snake-gold.svg?color_snake=%23f2d675&color_dots=%230a0a0a,%233a2f10,%23705a1c,%23b3902c,%23d4af37&color_dots_border=%23000000

      - name: Push snake svg to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
